app:
  build: ./build-app
  ports:
    - "8000:80"
  volumes:
    - /sync/build-app/app:/usr/share/nginx/html
api:
  build: ./build-api
  ports:
    - "8083:8083"
  volumes:
    - /sync/build-api/app:/app
#test:
#  build: build-test
#  volumes:
#    - /sync/build-test/test:/test
