name 'jenkins_config'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures jenkins_config'
long_description 'Installs/Configures jenkins_config'
version '0.1.0'
