# # -*- mode: ruby -*-
# # vi: set ft=ruby :
Vagrant.configure("2") do |config|
  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
    v.cpus = 2
  end
  config.vm.hostname = "Jenkins"
  # Choose host
  config.vm.box = "bento/ubuntu-16.04"
  # forward ports
  config.vm.network "forwarded_port", guest:80, host:80
  config.vm.network "forwarded_port", guest:443, host:443
  config.vm.network "forwarded_port", guest:8080, host:8080
  # Install Chef
  config.vm.provision "shell", inline: "sudo apt-get install curl"
  config.vm.provision "shell", inline: "curl https://omnitruck.chef.io/install.sh | sudo bash -s -- -P chefdk -c stable -v 0.16.28"
  config.vm.provision "shell", inline: "sudo chef-client --local-mode --runlist 'recipe[jenkins::master]'"
  config.vm.provision "shell", inline: "sudo chef-client --local-mode --runlist 'recipe[jenkins_config]'"
  # Synced folders
  config.vm.synced_folder "cookbooks/", "/home/vagrant/cookbooks"
end
